services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=8.0"
      MONGODB_URI: "mongodb://${MONGO_USER:-app}:${MONGO_PASSWORD:-!ChangeMe!}@mongodb:27017"
      MONGODB_DB: "${MONGO_DATABASE:-wasyoku}"
      SERVER_NAME: ":80"

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMeToo!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-!ChangeMeToo!}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-app}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-!ChangeMe!}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-wasyoku}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mongodb_data:/data/db:rw
###< doctrine/mongodb-odm-bundle ###

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: app
      PMA_PASSWORD: '!ChangeMe!'
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
###> doctrine/mongodb-odm-bundle ###
  mongodb_data:
###< doctrine/mongodb-odm-bundle ###